### ISSUE TITLE
Can not run in Fedora 24

### ISSUE THREAD

**Issue by LonelySpooky** [liresearchgroup/chronusq_public#8]
Hi, It looks like my compilation went well, but I'm receiving only this message when I try to run the software:
```
[henrique@localhost tests] $ python2 rununit.py -h
Traceback (most recent call last):
  File "rununit.py", line 4, in <module>
    from chronusq import *
  File "/home/henrique/Build/chronusq_public/tests/chronusq.py", line 33, in <module>
    from parse.parseInput import parseInput
  File "/home/henrique/Build/chronusq_public/build/src/python/parse/parseInput.py", line 27, in <module>
    import configparser
ImportError: No module named configparser
```
Any idea?

**Comment by LonelySpooky** [comment]
Well, I had to change configparser in line 27 to ConfigParser and it worked.

**Comment by LonelySpooky** [comment]
Never mind. It crashes in another step.
```
[henrique@localhost tests] $ python rununit.py -h

  python runtests.py [-o --option=]

  Options:
    -h, --help        Print usage instructions
    -s, --silent      Disable Print
    -k, --kill        Stop testing if a job fails
    --type=           Determines types of tests to run. Multiple options
                      can be specified by separating with a comma.
                      3 classes of tests  = [SCF,RESP,RT] 
                      Specify References  = [RHF,UHF,CUHF,GHF]
                                            [RKS,UKS,SLATER,LSDA,SVWN5]
                      Reference and Type  = [(R|U|CU)HF-SCF,HF-CIS,HF-RPA]
                                            [(R|U)KS-SCF,SCF-LSDA] 
                      Dipole Field        = [DField]
    --integrals=      Integral evaluation = [incore] or [direct]
    --parallel=       Whether to run parallel jobs = [on] or [off]
    --size=           Size of jobs to run = [small] or [large] or [both]
                      [small] is the default
    --complex=        Complex Jobs = [yes] or [no] or [both]
                      [both] is the default
    --basis=          Only run tests for this basis set
                      [STO-3G,6-31G,cc-pVDZ,def2-SVPD]

[henrique@localhost tests] $ python rununit.py --type=SCF
running job: test0001_serial_incore.inp
/home/henrique/Build/chronusq_public/basis/sto3g.gbs
/home/henrique/Build/chronusq_public/basis/sto3g.gbs
Traceback (most recent call last):
  File "rununit.py", line 324, in <module>
    runUnit(doPrint)    
  File "rununit.py", line 150, in runUnit
    tests[k] = runCQ(i.infile,'')
  File "/home/henrique/Build/chronusq_public/tests/chronusq.py", line 121, in runCQ
    secDict = parseInput(workers,ifname)
  File "/home/henrique/Build/chronusq_public/build/src/python/parse/parseInput.py", line 162, in parseInput
    inputParser = configparser.ConfigParser()
NameError: global name 'configparser' is not defined
```

**Comment by wavefunction91** [comment]
Hello! We appreciate your interest in CQ. To preface, I'd like to say that some very large changes to the infrasturcture of the CQ code are coming very soon, with many substantional improvments. I encourage you to check back once the new Beta version is released. To get you going to the current version, it seems that you are missing a required package of CQ, configparser.

configparser is a python module that must be installed separately. If you have "pip" installed, you can install configparser

`pip install configparser`

but from Fedora, you should be able to install it directly through the package manager:

`sudo dnf install python-confgparser`

Please let me know if this helps.

**Comment by LonelySpooky** [comment]
Thank you! It worked nicely.

**Comment by wavefunction91** [comment]
Fantastic
